- id: 1c985a4a2e34434db7189ebc636ef346
  alias: VW CarID Climatisation on
  trigger:
  - entity_id: switch.wvwzzzauzfw911702_climatisation
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      message: Klimaanlegg er på
      title: E-Golf
    service: notify.ios_simon_sin_iphone_7
- id: 0bf3b9b711a54d7ea001482a7e635d03
  alias: VW CarID Climatisation off
  trigger:
  - entity_id: switch.wvwzzzauzfw911702_climatisation
    from: 'on'
    platform: state
    to: 'off'
  action:
  - data:
      message: Klimaanlegg er av
      title: E-Golf
    service: notify.ios_simon_sin_iphone_7
- id: 9336a921fb0543c1b347c460092f9c8e
  alias: VW CarID Charging
  trigger:
  - entity_id: switch.vw_carid_charging
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      message: Batteriet lades
      title: E-Golf
    service: notify.ios_simon_sin_iphone_7
- id: 8ffa860b40474b288aafc9e9fee4ce21
  alias: VW CarID Battery fully charged
  trigger:
  - above: '99'
    entity_id: sensor.wvwzzzauzfw911702_battery_level
    platform: numeric_state
  action:
  - data:
      message: Batteriet er 100%
      title: E-Golf
    service: notify.ios_simon_sin_iphone_7
- id: '1540576707188'
  alias: Vacuum weekdays
  trigger:
  - at: '11:00'
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  - condition: template
    value_template: '{{ states("device_tracker.simonsiniphone7_2") != "home" }}'
  action:
  - data: {}
    service: script.vacuum_livingroom
- id: '1540900686576'
  alias: VW Charging stopped
  trigger:
  - entity_id: switch.wvwzzzauzfw911702_charging
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Lading avbrutt
      title: E-Golf
    service: notify.ios_simon_sin_iphone_7
- id: '1541457544610'
  alias: tv off when lights off
  trigger:
  - entity_id: light.livingroom_lights
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - after: '21:30'
    before: 06:00
    condition: time
  action:
  - data:
      entity_id: remote.harmony_hub
    service: remote.turn_off
- id: d7fd9c9686bb4e56a2fe5e8268cc1b58
  alias: dim lights at sundown
  trigger:
  - event: sunset
    offset: 00:30:00
    platform: sun
  condition:
  - condition: state
    entity_id: light.livingroom_lights
    state: 'on'
  action:
  - data:
      brightness: '45'
      color_temp: '450'
      entity_id: light.livingroom_lights
      transition: '900'
    service: light.turn_on
- id: '1542311037089'
  alias: Tv off at night
  trigger:
  - at: 03:00
    platform: time
  condition:
  - condition: state
    entity_id: light.livingroom_lights
    state: 'off'
  action:
  - service: script.turnofftv
- id: '1543413624056'
  alias: Heater on before bed
  trigger:
  - at: '20:30'
    platform: time
  condition:
  - above: '-1000'
    below: '15'
    condition: numeric_state
    entity_id: sensor.weather_temperature
  action:
  - data:
      entity_id: switch.tradfri_control_outlet
    service: switch.turn_on
- id: '1543414096425'
  alias: Heater off in the morning
  trigger:
  - at: 07:00
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - data:
      entity_id: switch.tradfri_control_outlet
    service: switch.turn_off
- id: '1549906953663'
  alias: Radiolights on
  trigger:
  - entity_id: light.livingroom_lights
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.sonoff2
    service: switch.turn_on
- id: '1549907033692'
  alias: Radiolights off
  trigger:
  - entity_id: light.livingroom_lights
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: switch.sonoff2
    service: switch.turn_off
- id: '1552081279977'
  alias: Tøm støvsuger
  trigger:
  - entity_id: vacuum.vacuum
    from: cleaning
    platform: state
    to: docked
  condition:
  - after: '11:00'
    before: '12:00'
    weekday:
    - wed
    condition: time
  action:
  - data: {}
    service: script.empty_vacuum
- id: '1552136838463'
  alias: Lys holder seg på
  trigger:
  - entity_id: light.tradfri_bulb_e27_ws_opal_980lm_2
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - after: sunset
    after_offset: -00:30:00
    before_offset: 00:30:00
    condition: sun
  action:
  - data:
      brightness_pct: '80'
      entity_id: light.spotter_stue
    service: light.turn_on
  - delay: '30'
  - data:
      entity_id: light.spotter_stue
    service: light.turn_off
- id: '1552140807307'
  alias: Alarm 0800
  trigger:
  - at: 06:50
    platform: time
  condition:
  - condition: state
    entity_id: input_select.alarm
    state: '08.00'
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - data:
      entity_id: media_player.kitchen
      source: NRK P3
    service: media_player.select_source
  - data:
      entity_id: media_player.kitchen
      volume_level: '0.1'
    service: media_player.volume_set
  - delay: 05:00
  - data:
      entity_id: media_player.bedroom
      volume_level: '0.12'
    service: media_player.volume_set
- id: '1552140807307'
  alias: Alarm 0900
  trigger:
  - at: 07:50
    platform: time
  condition:
  - condition: state
    entity_id: input_select.alarm
    state: '09.00'
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - data:
      entity_id: media_player.kitchen
      source: NRK P3
    service: media_player.select_source
  - data:
      entity_id: media_player.kitchen
      volume_level: '0.1'
    service: media_player.volume_set
  - delay: 05:00
  - data:
      entity_id: media_player.bedroom
      volume_level: '0.12'
    service: media_player.volume_set
