homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 50
  unit_system: metric
  time_zone: !secret timezone
  customize: !include customize.yaml


frontend: !include frontend.yaml
config: # Enables configuration UI
updater: # Optional, allows Home Assistant developers to focus on popular components.
discovery: # Discover some devices automatically
conversation: # Allows you to issue voice commands from the frontend in enabled browsers
history: # Enables support for tracking state changes over time
logbook: # View all events in a logbook
map: # Enables a map showing the location of tracked devices
ios:
sun: # Track the sun
system_health:

zone:
  - name: Haakonsvern
    latitude: !secret hos_latitude
    longitude: !secret hos_longitude
    radius: 500
    icon: mdi:castle
  - name: SKSK
    icon: mdi:school
    latitude: !secret sksk_latitude
    longitude: !secret sksk_longitude
    radius: 300
    
lovelace:
  mode: yaml

# Sensors
sensor: !include sensors.yaml

# Se
binary_sensor:
  - platform: workday
    country: "NO"
    workdays: [mon, tue, wed, thu, fri]
    
# Text to speech
tts:
  - platform: google
    base_url: !secret tts_url

# CLOUD
cloud:
  alexa:
    filter:
      include_domains:
        - switch
      include_entities:
        - switch.vacuum

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
light: !include lights.yaml

# XIAOMI-VACUUM
vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.144
    token: !secret vacuum_token
    name: Vacuum

# DUCKDNS/SSL
http:
  base_url: !secret http_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  api_password: !secret http_password
  trusted_networks:
    - 192.168.1.1
  login_attempts_threshold: 5

# CONFIGURATOR
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret configurator_url
  terminal:
    title: Terminal
    icon: mdi:console
    url: !secret ssh_address

# TRACKING
device_tracker:
  # - platform: icloud
    # username: !secret ios_username
    # password: !secret ios_password
    # account_name: Simon
  - platform: nmap_tracker
    hosts: 192.168.1.0/24
    home_interval: 10

    
homekit:
  filter:
    include_entities:
      - switch.vacuum
      - switch.wvwzzzauzfw911702_climatisation
      - switch.wvwzzzauzfw911702_window_heater
      - script.bedtime

# SWITCHES
switch:
  - platform: template
    switches:
      vacuum:
        friendly_name: Vacuum
        value_template: "{{ is_state('vacuum.Vacuum', 'cleaning') }}"
        turn_on:
          service: script.vacuum_livingroom
        turn_off:
          service: vacuum.return_to_base
          entity_id: vacuum.Vacuum
          
      find_phone:
        friendly_name: Find My Phone
        value_template: "{{ is_state('input_boolean.find_my_phone', 'on') }}"
        turn_on:
          service: device_tracker.icloud_lost_iphone
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.find_phone
          
  - platform: wake_on_lan
    mac_address: "10:C3:7B:6E:02:03"
    
  - platform: mqtt
    name: "Sonoff1"
    command_topic: "cmnd/sonoff1/power"
    state_topic: "stat/sonoff1/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
    
  - platform: mqtt
    name: "Sonoff2"
    command_topic: "cmnd/sonoff2/power"
    state_topic: "stat/sonoff2/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

# BOOLEANS
input_boolean:
  find_my_phone:
    name: Find My Phone
    initial: off
    icon: mdi:smartphone-wireless
    
input_select:
  alarm:
    name: Når starter du
    options:
      # - "07.30"
      - "08.00"
      # - "08.30"
      - "09.00"
      # - "09.30"
      # - "10.00"
      # - "10.30"
      # - "11.00"
    initial: "08.00"
    icon: mdi:alarm

# Example configuration.yaml entry for the Telegram Bot
#telegram_bot:
#  - platform: polling
#    api_key: !secret telegram_api
#    allowed_chat_ids:
#      - !secret telegram_chatid

# Example configuration.yaml entry for the notifier
#notify:
#  - name: Telegram
#   platform: telegram
#   chat_id: !secret telegram_chatid

# VW CAR
# volkswagen_carnet:
  # username: !secret carnet_id
  # password: !secret carnet_password
  # update_interval: 
    # minutes: 5 

