- platform: group
  name: Spotter Stue
  entities:
    - light.tradfri_bulb_gu10_ws_400lm_3
    - light.tradfri_bulb_gu10_ws_400lm_4
    - light.tradfri_bulb_gu10_ws_400lm_5
    
- platform: group
  name: Livingroom Lights
  entities:
    - light.tradfri_bulb_e27_ws_opal_980lm
    - light.tradfri_bulb_e27_ws_opal_980lm_2
    - light.tradfri_bulb_e27_cws_opal_600lm
    - light.spotter_stue
    - light.tradfri_bulb_e14_ws_opal_400lm_7
    
- platform: group
  name: Bedroom Lights
  entities:
    - light.tradfri_bulb_gu10_w_400lm
    - light.tradfri_bulb_gu10_w_400lm_2
    - light.tradfri_bulb_gu10_w_400lm_3
    
- platform: group
  name: Toras Lights
  entities:
    - light.tradfri_light7e2165520440000965551
    
- platform: group
  name: All Lights
  entities:
    - light.livingroom_lights
    - light.bedroom_lights
    - light.toras_lights