resources:
  - url: /local/mini-media-player-bundle.js?v=0.9.2
    type: module

############## HOME FANE ############

title: Home
views:
  - title: default_view
    icon: mdi:home
    cards:
      - type: glance
        entities:
          - entity: device_tracker.simonsiniphone7_2
            name: Simon
            icon: mdi:human-handsup
          - entity: device_tracker.julie_sin_iphone
            name: Julie
            icon: mdi:human-female
          - entity: device_tracker.torasiniphone
            name: Tora
            icon: mdi:human-pregnant
          - entity: device_tracker.wvwzzzauzfw911702
            name: VW
      - type: horizontal-stack
        cards:
          - type: light
            entity: light.livingroom_lights
            tap_action: 
              action: toggle
            hold_action: more-info
            name: Stue
          - type: light
            entity: light.bedroom_lights
            tap_action: 
              action: toggle
            name: Soverom
      - type: entities
        #title: Alarm
        show_header_toggle: false
        entities:
          - input_select.alarm
          
          # - type: light
            # entity: light.toras_lights
            # name: Toras Soverom
      # - type: glance
        # title: E-Golf
        # show_header_toggle: false
        # entities:
          # - entity: switch.wvwzzzauzfw911702_charging
            # tap_action: 
              # action: toggle
            # name: Lading
          # - entity: switch.wvwzzzauzfw911702_climatisation
            # tap_action: 
              # action: toggle
            # name: Klima
          # - entity: switch.wvwzzzauzfw911702_window_heater
            # tap_action: 
              # action: toggle
            # name: Vindu
            # icon: mdi:snowflake
          # - entity: sensor.wvwzzzauzfw911702_battery_level
            # name: Batteri
      - type: glance
        title: "Støvsuger"
        show_header_toggle: false
        show_state: false
        entities:
        - entity: switch.vacuum
          name: Bryter
          icon: mdi:robot-vacuum
          tap_action: 
              action: toggle
        # - entity: vacuum.vacuum
          # name: Info
        - entity: automation.vacuum_weekdays
          name: Daglig
          tap_action: 
              action: toggle
        - entity: script.vacuum_kitchen
          name: Kjøkken
          icon: mdi:silverware-fork-knife
          tap_action:
            action: toggle
        - entity: script.empty_vacuum
          name: Tøm
          icon: mdi:delete
          tap_action:
            action: toggle
      - type: glance
        title: "Vær"
        show_header_toggle: true
        entities:
          - sensor.weather_temperature
          - sensor.weather_wind_speed
          - sensor.weather_wind_direction
      - type: glance
        #title: "Klima"
        entities:
        - entity: sensor.sn1_temperature
          name: Temp Stue
        - entity: sensor.sn1_humidity
          name: Fuktighet Stue
          icon: mdi:water-percent
        - entity: sensor.sn2_temperature
          name: Temp Sove
        - entity: sensor.sn2_humidity
          name: Fuktighet Sove
          icon: mdi:water-percent
      - type: vertical-stack
        cards:
        - type: custom:mini-media-player
          entity: media_player.kitchen
          icon: mdi:speaker-wireless
          show_source: small
          hide_power: true
          name: Sonos | Kjøkken
          show_tts: google
        - type: custom:mini-media-player
          entity: media_player.bathroom
          icon: mdi:speaker-wireless
          show_source: small
          hide_power: true
          name: Sonos | Bad
          show_tts: google
        # - type: custom:mini-media-player
          # entity: media_player.soverom
          # icon: mdi:speaker-wireless
          # show_source: small
          # hide_power: true
          # name: Sonos | Soverom
          # show_tts: google
      

        
############## STUE FANE ###############
  - title: Stue
    icon: mdi:sofa
    cards:
      - type: vertical-stack
        cards:
        - type: markdown
          content: >
            ## LYS
            
        - type: horizontal-stack
          cards:
            - type: entity-button
              entity: light.tradfri_bulb_e27_ws_opal_980lm
              tap_action: 
                action: toggle
              name: Spisebord
            - type: entity-button
              entity: light.tradfri_bulb_e27_ws_opal_980lm_2
              tap_action:
                action: toggle
              name: Sofa
            - type: entity-button
              entity: light.spotter_stue
              tap_action: 
                action: toggle
              name: Spotter
        
        - type: horizontal-stack
          cards:
            - type: entity-button
              entity: script.relax
              tap_action: 
                action: toggle
              name: Dim
            - type: entity-button
              entity: script.leselys
              tap_action: 
                action: toggle
              name: Leselampe
            - type: entity-button
              entity: script.everyday
              tap_action: 
                action: toggle
              name: Bright
        - type: vertical-stack
          cards:
            - type: glance
              title: TV
              show_header_toggle: true
              entities:
                - entity: script.watchsmarttv
                  name: Chromecast
                  tap_action: 
                    action: toggle
                - entity: script.watchappletv
                  name: Apple TV
                  tap_action: 
                    action: toggle
                - entity: script.playstation
                  name: Playstation
                  tap_action: 
                    action: toggle
                - entity: script.turnofftv
                  name: Turn off
                  tap_action: 
                    action: toggle
              show_state: false
          # - type: glance
            # entities:
              # - entity: script.volume_down
                # tap_action: toggle
              # - entity: script.volume_up
                # tap_action: toggle
              # - entity: script.volume_mute
                # tap_action: toggle
              # - entity: script.play
                # tap_action: toggle
              # - entity: script.pause
                # tap_action: toggle
            # show_state: false
            # show_name: false
            - type: horizontal-stack
              cards:
              - type: entity-button
                entity: script.volume_down
                name: Down
                tap_action: 
                  action: toggle
              - type: entity-button
                entity: script.volume_up
                name: Up
                tap_action: 
                  action: toggle
              - type: entity-button
                entity: script.volume_mute
                name: Mute
                tap_action: 
                  action: toggle
              - type: entity-button
                entity: script.play
                tap_action: 
                  action: toggle
              - type: entity-button
                entity: script.pause
                tap_action: 
                  action: toggle
              - type: entity-button
                entity: script.effect
                tap_action: 
                  action: toggle
                name: effect
      - type: vertical-stack
        cards:
        - type: custom:mini-media-player
          entity: media_player.kitchen
          icon: mdi:speaker-wireless
          show_source: small
          hide_power: true
          name: Sonos | Kjøkken
          show_tts: google
        - type: custom:mini-media-player
          entity: media_player.bathroom
          icon: mdi:speaker-wireless
          show_source: small
          hide_power: true
          name: Sonos | Bad
          show_tts: google
        - type: custom:mini-media-player
          entity: media_player.soverom
          icon: mdi:speaker-wireless
          show_source: small
          hide_power: true
          name: Sonos | Soverom
          show_tts: google
 
########## SOVEROM FANE #############
  - title: Soverom
    icon: mdi:hotel
    cards:
      - type: horizontal-stack
        cards:
          - type: entity-button
            entity: light.bedroom_lights
            name: Soverom
            tap_action: 
              action: toggle
          - type: entity-button
            entity: script.bedroom_relax
            name: Relax
            tap_action: 
              action: toggle
          - type: entity-button
            entity: script.bedroom_everyday
            name: Everyday
            tap_action: 
              action: toggle
      - type: glance
        name: Varmeovn
        entities: 
          - entity: switch.tradfri_control_outlet
            name: Bryter
            icon: mdi:radiator
            tap_action: 
              action: toggle
          - entity: automation.heater_on_before_bed
            name: Varme kveld
            icon: mdi:calendar-clock
            tap_action: 
              action: toggle
      - type: media-control
        entity: media_player.bathroom
      - type: glance
        title: Brytere
        entities:
        - entity: switch.sonoff1
          name: Sonoff 1
        - entity: switch.sonoff2
          name: Sonoff 2
        
############ TELEFON FANE ############
  - title: Telefon
    icon: mdi:phone
    cards:
      - type: glance
        entities:
          - entity: device_tracker.simonsiniphone7
            name: Simon
            icon: mdi:human-handsup
          - entity: device_tracker.julie_sin_iphone
            name: Julie
            icon: mdi:human-female
      - type: entities
        entities:
          - sensor.julie_sin_iphone_battery_level
          - sensor.julie_sin_iphone_battery_state
          - switch.find_phone
      - type: entity-button
        title: PC
        entity: switch.wake_on_lan
          
  - title: Volkswagen
    icon: mdi:car
    cards:
      - type: entities
        title: Volkswagen Switches
        show_header_toggle: false
        entities:
          - switch.wvwzzzauzfw911702_charging
          - switch.wvwzzzauzfw911702_climatisation
          - switch.wvwzzzauzfw911702_window_heater
          - lock.wvwzzzauzfw911702_doors_locked
          - lock.wvwzzzauzfw911702_trunk_locked
          
      - type: entities
        title: Volkswagen Information
        show_header_toggle: false
        entities:
          - sensor.wvwzzzauzfw911702_battery_level
          - sensor.wvwzzzauzfw911702_charging_time_left
          - sensor.wvwzzzauzfw911702_odometer
          - sensor.wvwzzzauzfw911702_electric_range
          - sensor.wvwzzzauzfw911702_last_connected
          - sensor.wvwzzzauzfw911702_service_inspection
          - sensor.wvwzzzauzfw911702_climatisation_target_temperature
          - binary_sensor.wvwzzzauzfw911702_parking_light
          - binary_sensor.wvwzzzauzfw911702_external_power
          - binary_sensor.wvwzzzauzfw911702_climatisation_without_external_power
          
      - type: entities
        title: Volkswagen Location
        show_header_toggle: false
        entities:
          - device_tracker.wvwzzzauzfw911702
      - type: entities
        entities:
          - automation.vw_carid_battery_fully_charged
          - automation.vw_carid_climatisation_on
          - automation.vw_carid_climatisation_off
          - automation.vw_carid_charging
          
############ AUTOMASJONER FANE ###############
  - title: Automasjoner
    icon: mdi:home-automation
    cards:
      - type: entities
        title: all automations
        show_header_toggle: true
        entities:
          - automation.vw_carid_battery_fully_charged
          - automation.vw_carid_charging
          - automation.vw_carid_climatisation_off
          - automation.vw_carid_climatisation_on
          - automation.vw_charging_stopped
          - automation.vacuum_weekdays
          - automation.tv_off_when_lights_off
          - automation.tom_stovsuger
          - automation.heater_off_in_the_morning
          - automation.heater_on_before_bed
          
  - title: Floor-plan
    icon: mdi:map
    cards:
      - type: picture-elements
        image: /local/second-floor.png
        elements:
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.tradfri_bulb_e27_ws_opal_980lm_2
            style:
              top: 34%
              left: 31%
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.spotter_stue
            style:
              top: 50%
              left: 85%
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.tradfri_bulb_e27_ws_opal_980lm
            style:
              top: 80%
              left: 49%
          - type: state-icon
            tap_action:
              action: toggle
            entity: switch.vacuum
            style:
              top: 92%
              left: 67%
          - type: state-label
            tap_action:
              action: toggle
            entity: sensor.weather_temperature
            style:
              top: 15%
              left: 5%
          - type: state-label
            tap_action:
              action: toggle
            entity: sensor.weather_wind_speed
            style:
              top: 22%
              left: 6%
      - type: picture-elements
        image: /local/third-floor.png
        elements:
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.bedroom_lights
            style:
              top: 32%
              left: 16%
          - type: state-icon
            tap_action:
              action: toggle
            entity: switch.tradfri_control_outlet
            style:
              top: 45%
              left: 5%
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.toras_lights
            style:
              top: 68%
              left: 16%