#### LOVELACE ####

resources:
  - url: /local/mini-media-player-bundle.js
    type: module
  - url: /local/time-input-row.js
    type: js

############## HOME FANE ############

title: Home
views:
  - title: default_view
    icon: mdi:home
    cards:
      
      ## TRACKERS ##
      - type: glance
        entities:
          - entity: device_tracker.simonsiniphone7_2
            name: Simon
            icon: mdi:human-handsup
          - entity: device_tracker.julie_sin_iphone
            name: Julie
            icon: mdi:human-female
          - entity: device_tracker.torasiniphone
            name: Tora
            icon: mdi:human-pregnant
          - entity: device_tracker.wvwzzzauzfw911702
            name: VW
            icon: mdi:car
            
      ## LIGHTS ###      
      - type: horizontal-stack
        cards:
          - type: light
            entity: light.livingroom_lights
            tap_action: 
              action: toggle
            hold_action: more-info
            name: Stue
          - type: light
            entity: light.bedroom_lights
            tap_action: 
              action: toggle
            name: Soverom
      - type: entities
        #title: Alarm
        show_header_toggle: false
        entities:
          - input_select.alarm
    
          
    #### EGOLF KONTROLL ####
      # - type: glance
        # title: E-Golf
        # show_header_toggle: false
        # entities:
          # - entity: switch.wvwzzzauzfw911702_charging
            # tap_action: 
              # action: toggle
            # name: Lading
          # - entity: switch.wvwzzzauzfw911702_climatisation
            # tap_action: 
              # action: toggle
            # name: Klima
          # - entity: switch.wvwzzzauzfw911702_window_heater
            # tap_action: 
              # action: toggle
            # name: Vindu
            # icon: mdi:snowflake
          # - entity: sensor.wvwzzzauzfw911702_battery_level
            # name: Batteri
            
      ## VACUUM ###      
      - type: glance
        title: "Støvsuger"
        show_header_toggle: false
        show_state: false
        entities:
        - entity: switch.vacuum
          name: Støvsug
          icon: mdi:robot-vacuum
          tap_action: 
              action: toggle
        - entity: switch.vacuum_weekdays
          name: Daglig
          tap_action: 
              action: toggle
        - entity: script.vacuum_kitchen
          name: Kjøkken
          icon: mdi:silverware-fork-knife
          tap_action:
            action: toggle
        - entity: script.empty_vacuum
          name: Tøm
          icon: mdi:delete
          tap_action:
            action: toggle
            
      
      ## WEATHER SENSORS ##
      - type: glance
        title: "Vær"
        show_header_toggle: true
        entities:
          - sensor.weather_temperature
          - sensor.weather_wind_speed
          - sensor.weather_wind_direction
          
      ## INDOOR CLIMATE SENSORS ##
      - type: glance
        #title: "Klima"
        entities:
        - entity: sensor.livingroom_temperature
          name: Temp Stue
        - entity: sensor.livingroom_humidity
          name: Fuktighet Stue
          icon: mdi:water-percent
        - entity: sensor.bedroom_temperature
          name: Temp Sove
        - entity: sensor.bedroom_humidity
          name: Fuktighet Sove
          icon: mdi:water-percent
      
      ## SONOS MEDIA CONTROL ##
      - type: vertical-stack
        cards:
        - type: custom:mini-media-player
          entity: media_player.kitchen
          icon: mdi:speaker-wireless
          show_source: small
          hide:
            power: true
          name: Stue
          tts: 
            platform: google
            volume: 1
          artwork: cover
          info: short
          max_volume: 70
          sonos:
            show_group_count: true
            entities:
              - entity_id: media_player.kitchen
                name: Stue
              - entity_id: media_player.bathroom
                name: Bad
              - entity_id: media_player.soverom
                name: Soverom
                
        - type: custom:mini-media-player
          entity: media_player.bathroom
          icon: mdi:speaker-wireless
          show_source: small
          hide:
            power: true
          name: Bad
          tts: 
            platform: google
            volume: 1
          artwork: cover
          info: short
          max_volume: 70
          sonos:
            show_group_count: true
            entities:
              - entity_id: media_player.bathroom
                name: Bad
              - entity_id: media_player.kitchen
                name: Stue
              - entity_id: media_player.soverom
                name: Soverom
      

        
############## STUE FANE ###############
  - title: Stue
    icon: mdi:sofa
    cards:
    
      ## LIVINGROOM LIGHTS ##
      - type: vertical-stack
        cards:
        - type: markdown
          content: >
            ## LYS
          
        - type: horizontal-stack
          cards:
            - type: entity-button
              entity: light.dining_room
              tap_action: 
                action: toggle
              name: Spisebord
            - type: entity-button
              entity: light.couch
              tap_action:
                action: toggle
              name: Sofa
            - type: entity-button
              entity: light.spotter_stue
              tap_action: 
                action: toggle
              name: Spotter
        
        ## LIGHT MOOD SCRIPTS ##
        - type: horizontal-stack
          cards:
            - type: entity-button
              entity: script.relax
              tap_action: 
                action: toggle
              name: Dim
            - type: entity-button
              entity: script.leselys
              tap_action: 
                action: toggle
              name: Leselampe
            - type: entity-button
              entity: script.everyday
              tap_action: 
                action: toggle
              name: Bright
              
        ## TV CONTROL ##
        - type: vertical-stack
          cards:
            - type: glance
              title: TV
              show_header_toggle: true
              entities:
                - entity: script.watchsmarttv
                  name: Chromecast
                  tap_action: 
                    action: toggle
                - entity: script.watchappletv
                  name: Apple TV
                  tap_action: 
                    action: toggle
                - entity: script.playstation
                  name: Playstation
                  tap_action: 
                    action: toggle
                - entity: script.turnofftv
                  name: Turn off
                  tap_action: 
                    action: toggle
              show_state: false
        
        
            - type: horizontal-stack
              cards:
              - type: entity-button
                entity: script.volume_down
                name: Down
                tap_action: 
                  action: toggle
              - type: entity-button
                entity: script.volume_up
                name: Up
                tap_action: 
                  action: toggle
              - type: entity-button
                entity: script.volume_mute
                name: Mute
                tap_action: 
                  action: toggle
              - type: entity-button
                entity: script.play
                tap_action: 
                  action: toggle
              - type: entity-button
                entity: script.pause
                tap_action: 
                  action: toggle
              - type: entity-button
                entity: script.effect
                tap_action: 
                  action: toggle
                name: effect
      
      ## LIVINGROOM RADIATOR ##
      - type: glance
        #title: Strøm
        entities:
        - entity: switch.sonoffpow2
          name: POW 2
          icon: mdi:radiator
        - entity: sensor.pow2_today
          name: Today
          icon: mdi:power-plug
          
      ## PLANT MONITORING ##
      - type: plant-status
        entity: plant.plante
        
      ## SONOS MEDIA CONTROL ##
      - type: vertical-stack
        cards:
        - type: custom:mini-media-player
          entity: media_player.kitchen
          icon: mdi:speaker-wireless
          show_source: small
          hide:
            power: true
          name: Stue
          tts: 
            platform: google
            volume: 1
          artwork: cover
          info: short
          max_volume: 70
          sonos:
            show_group_count: true
            entities:
              - entity_id: media_player.kitchen
                name: Stue
              - entity_id: media_player.bathroom
                name: Bad
              - entity_id: media_player.soverom
                name: Soverom
        - type: custom:mini-media-player
          entity: media_player.bathroom
          icon: mdi:speaker-wireless
          show_source: small
          hide:
            power: true
          name: Bad
          tts: 
            platform: google
            volume: 1
          artwork: cover
          info: short
          max_volume: 70
          sonos:
            show_group_count: true
            entities:
              - entity_id: media_player.bathroom
                name: Bad
              - entity_id: media_player.kitchen
                name: Stue
              - entity_id: media_player.soverom
                name: Soverom

                
              
########## SOVEROM FANE #############
  - title: Soverom
    icon: mdi:hotel
    cards:
    
      ## BEDROOM LIGHTS MOODS ##
      - type: horizontal-stack
        cards:
          - type: entity-button
            entity: light.bedroom_lights
            name: Soverom
            tap_action: 
              action: toggle
          - type: entity-button
            entity: script.bedroom_relax
            name: Relax
            tap_action: 
              action: toggle
          - type: entity-button
            entity: script.bedroom_everyday
            name: Everyday
            tap_action: 
              action: toggle
              
      ## BEDROOM HEATER CONTROL ##
      - type: glance
        name: Varmeovn
        entities: 
          - entity: switch.tradfri_control_outlet
            name: Bryter
            icon: mdi:radiator
            tap_action: 
              action: toggle
          - entity: automation.heater_on_before_bed
            name: Varme kveld
            icon: mdi:calendar-clock
            tap_action: 
              action: toggle
              
      ## SONOS MEDIA CONTROL ##
      - type: custom:mini-media-player
        entity: media_player.soverom
        icon: mdi:speaker-wireless
        show_source: small
        hide:
          power: true
        name: Soverom
        tts: 
          platform: google
          volume: 1
        artwork: cover
        info: short
        max_volume: 70
        sonos:
          show_group_count: true
          entities:
            - entity_id: media_player.bathroom
              name: Bad
            - entity_id: media_player.kitchen
              name: Stue
            - entity_id: media_player.soverom
              name: Soverom
              
      
      
  
#### BIL FANE ########  
  # - title: Volkswagen
    # icon: mdi:car
    # cards:
      # - type: entities
        # title: Volkswagen Switches
        # show_header_toggle: false
        # entities:
          # - switch.wvwzzzauzfw911702_charging
          # - switch.wvwzzzauzfw911702_climatisation
          # - switch.wvwzzzauzfw911702_window_heater
          # - lock.wvwzzzauzfw911702_doors_locked
          # - lock.wvwzzzauzfw911702_trunk_locked
          
      # - type: entities
        # title: Volkswagen Information
        # show_header_toggle: false
        # entities:
          # - sensor.wvwzzzauzfw911702_battery_level
          # - sensor.wvwzzzauzfw911702_charging_time_left
          # - sensor.wvwzzzauzfw911702_odometer
          # - sensor.wvwzzzauzfw911702_electric_range
          # - sensor.wvwzzzauzfw911702_last_connected
          # - sensor.wvwzzzauzfw911702_service_inspection
          # - sensor.wvwzzzauzfw911702_climatisation_target_temperature
          # - binary_sensor.wvwzzzauzfw911702_parking_light
          # - binary_sensor.wvwzzzauzfw911702_external_power
          # - binary_sensor.wvwzzzauzfw911702_climatisation_without_external_power
          
      # - type: entities
        # title: Volkswagen Location
        # show_header_toggle: false
        # entities:
          # - device_tracker.wvwzzzauzfw911702
      # - type: entities
        # entities:
          # - automation.vw_carid_battery_fully_charged
          # - automation.vw_carid_climatisation_on
          # - automation.vw_carid_climatisation_off
          # - automation.vw_carid_charging
          
############ AUTOMASJONER FANE ###############
  - title: Automasjoner
    icon: mdi:home-automation
    cards:
      - type: entities
        title: all automations
        show_header_toggle: true
        entities:
          - automation.vw_carid_battery_fully_charged
          - automation.vw_carid_charging
          - automation.vw_carid_climatisation_off
          - automation.vw_carid_climatisation_on
          - automation.vw_charging_stopped
          - automation.vacuum_weekdays
          - automation.tv_off_when_lights_off
          - automation.heater_off_in_the_morning
          - automation.heater_on_before_bed
   

########## FLOOR PLAN ############   
  - title: Floor-plan
    icon: mdi:map
    cards:
      - type: picture-elements
        image: /local/second-floor.png
        elements:
        
          ## FIRST FLOOR ##
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.couch
            style:
              top: 34%
              left: 31%
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.spotter_stue
            style:
              top: 50%
              left: 85%
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.dining_room
            style:
              top: 80%
              left: 49%
          - type: state-icon
            tap_action:
              action: toggle
            entity: switch.sonoff1
            style:
              top: 80%
              left: 38%
          - type: state-icon
            tap_action:
              action: toggle
            entity: switch.sonoff2
            style:
              top: 70%
              left: 38%
          - type: state-icon
            tap_action:
              action: toggle
            entity: switch.vacuum
            style:
              top: 8%
              left: 72%
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.kommode
            style:
              top: 8%
              left: 67%
          - type: state-icon
            tap_action:
              action: toggle
            entity: switch.wake_on_lan
            style:
              top: 90%
              left: 28%
          - type: state-label
            tap_action:
              action: toggle
            entity: sensor.weather_temperature
            style:
              top: 15%
              left: 5%
          - type: state-label
            tap_action:
              action: toggle
            entity: sensor.weather_wind_speed
            style:
              top: 22%
              left: 6%
          - type: state-icon
            tap_action:
              action: toggle
            entity: switch.sonoffpow2
            style:
              top: 20%
              left: 50%
              icon: mdi:radiator
              
      ## SECOND FLOOR ##
      - type: picture-elements
        image: /local/third-floor.png
        elements:
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.bedroom_lights
            style:
              top: 32%
              left: 16%
          - type: state-icon
            tap_action:
              action: toggle
            entity: switch.tradfri_control_outlet
            style:
              top: 45%
              left: 5%
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.toras_lights
            style:
              top: 68%
              left: 16%
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.ved_bod
            style:
              top: 42%
              left: 47%
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.utfor_vaskerom
            style:
              top: 42%
              left: 85%
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.trapp_oppe
            style:
              top: 20%
              left: 68%


  ####### TEST ############
  - title: TEST
    cards:
      - type: history-graph
        title: 'Temperaturer'
        hours_to_show: 24
        entities:
          - entity: sensor.sn2_temperature
            name: Soverom
          - entity: sensor.livingroom_temperature
            name: Stue
          - entity: sensor.weather_temperature
            name: Ute
      - type: sensor
        graph: line
        entity: sensor.weather_temperature
        name: Temperatur
      
      - type: glance
        title: Brytere
        entities:
        - entity: switch.sonoff1
          name: Sonoff 1
        - entity: switch.sonoff2
          name: Sonoff 2
        - entity: switch.wake_on_lan
          name: PC