resources:
  - url: /local/mini-media-player-bundle.js?v=0.9.2
    type: module

############## HOME FANE ############

title: Home
views:
  - title: default_view
    icon: mdi:home
    cards:
      - type: glance
        entities:
          - entity: device_tracker.simonsiniphone7
            name: Simon
            icon: mdi:human-handsup
          - entity: device_tracker.julie_sin_iphone
            name: Julie
            icon: mdi:human-female
          - entity: device_tracker.torasiniphone
            name: Tora
            icon: mdi:human-pregnant
          - entity: device_tracker.wvwzzzauzfw911702
            name: VW
      - type: horizontal-stack
        cards:
          - type: light
            entity: light.livingroom_lights
            tap_action: toggle
            hold_action: more-info
            name: Stue
          - type: light
            entity: light.bedroom_lights
            tap_action: toggle
            name: Soverom
      - type: glance
        title: E-Golf
        show_header_toggle: false
        entities:
          - entity: switch.wvwzzzauzfw911702_charging
            tap_action: toggle
            name: Lading
          - entity: switch.wvwzzzauzfw911702_climatisation
            tap_action: toggle
            name: Klima
          - entity: switch.wvwzzzauzfw911702_window_heater
            tap_action: toggle
            name: Vindu
            icon: mdi:snowflake
          - entity: sensor.wvwzzzauzfw911702_battery_level
            name: Batteri
      - type: glance
        title: "Søvsuger"
        show_header_toggle: false
        entities:
        - entity: switch.vacuum
          name: Bryter
          tap_action: toggle
        - entity: vacuum.vacuum
          name: Info
        - entity: automation.vacuum_weekdays
          name: Daglig støvsuging
          tap_action: toggle
        - entity: script.bedtime
          name: Leggetid
          tap_action: toggle
      - type: glance
        title: "Vær"
        show_header_toggle: true
        entities:
          - sensor.weather_temperature
          - sensor.weather_wind_speed
          - sensor.weather_wind_direction
      - type: custom:mini-media-player
        entity: media_player.kitchen
        icon: mdi:speaker-wireless
        show_source: small
        hide_power: true
        name: Sonos | Kjøkken
        show_tts: google
        
############## STUE FANE ###############
  - title: Stue
    icon: mdi:sofa
    cards:
      - type: vertical-stack
        cards:
        - type: markdown
          content: >
            ## LYS
            
        - type: horizontal-stack
          cards:
            - type: entity-button
              entity: light.tradfri_bulb_e27_ws_opal_980lm
              tap_action: toggle
              name: Spisebord
            - type: entity-button
              entity: light.tradfri_bulb_e27_ws_opal_980lm_2
              tap_action: toggle
              name: Sofa
            - type: entity-button
              entity: light.spotter_stue
              tap_action: toggle
              name: Spotter
        
        - type: horizontal-stack
          cards:
            - type: entity-button
              entity: script.relax
              tap_action: toggle
              name: Dim
            - type: entity-button
              entity: light.livingroom_lights
              tap_action: toggle
              name: Alle stuelys
            - type: entity-button
              entity: script.everyday
              tap_action: toggle
              name: Bright
        - type: vertical-stack
          cards:
            - type: glance
              title: TV
              show_header_toggle: true
              entities:
                - entity: script.watchsmarttv
                  name: Chromecast
                  tap_action: toggle
                - entity: script.watchappletv
                  name: Apple TV
                  tap_action: toggle
                - entity: script.playstation
                  name: Playstation
                  tap_action: toggle
                - entity: script.turnofftv
                  name: Turn off
                  tap_action: toggle
              show_state: false
          # - type: glance
            # entities:
              # - entity: script.volume_down
                # tap_action: toggle
              # - entity: script.volume_up
                # tap_action: toggle
              # - entity: script.volume_mute
                # tap_action: toggle
              # - entity: script.play
                # tap_action: toggle
              # - entity: script.pause
                # tap_action: toggle
            # show_state: false
            # show_name: false
            - type: horizontal-stack
              cards:
              - type: entity-button
                entity: script.volume_down
                name: Down
                tap_action: toggle
              - type: entity-button
                entity: script.volume_up
                name: Up
                tap_action: toggle
              - type: entity-button
                entity: script.volume_mute
                name: Mute
                tap_action: toggle
              - type: entity-button
                entity: script.play
                tap_action: toggle
              - type: entity-button
                entity: script.pause
                tap_action: toggle
              - type: entity-button
                entity: script.effect
                tap_action: toggle
                name: effect
      - type: vertical-stack
        cards:
          - type: media-control
            entity: media_player.kitchen
          - type: media-control
            entity: media_player.stue
        
############ TELEFON FANE ############
  - title: Telefon
    icon: mdi:phone
    cards:
      - type: glance
        entities:
          - entity: device_tracker.simonsiniphone7
            name: Simon
            icon: mdi:human-handsup
          - entity: device_tracker.julie_sin_iphone
            name: Julie
            icon: mdi:human-female
      - type: entities
        entities:
          - sensor.julie_sin_iphone_battery_level
          - sensor.julie_sin_iphone_battery_state
          - switch.find_phone
      - type: entity-button
        title: PC
        entity: switch.wake_on_lan
          
########## SOVEROM FANE #############
  - title: Soverom
    icon: mdi:hotel
    cards:
      - type: horizontal-stack
        cards:
          - type: entity-button
            entity: light.bedroom_lights
            name: Soverom
            tap_action: toggle
          - type: entity-button
            entity: script.bedroom_relax
            name: Relax
            tap_action: toggle
          - type: entity-button
            entity: script.bedroom_everyday
            name: Everyday
            tap_action: toggle
              
      - type: media-control
        entity: media_player.bathroom
  - title: Volkswagen
    icon: mdi:car
    cards:
      - type: entities
        title: Volkswagen Switches
        show_header_toggle: false
        entities:
          - switch.wvwzzzauzfw911702_charging
          - switch.wvwzzzauzfw911702_climatisation
          - switch.wvwzzzauzfw911702_window_heater
          - lock.wvwzzzauzfw911702_doors_locked
          - lock.wvwzzzauzfw911702_trunk_locked
          
      - type: entities
        title: Volkswagen Information
        show_header_toggle: false
        entities:
          - sensor.wvwzzzauzfw911702_battery_level
          - sensor.wvwzzzauzfw911702_charging_time_left
          - sensor.wvwzzzauzfw911702_odometer
          - sensor.wvwzzzauzfw911702_electric_range
          - sensor.wvwzzzauzfw911702_last_connected
          - sensor.wvwzzzauzfw911702_service_inspection
          - sensor.wvwzzzauzfw911702_climatisation_target_temperature
          - binary_sensor.wvwzzzauzfw911702_parking_light
          - binary_sensor.wvwzzzauzfw911702_external_power
          - binary_sensor.wvwzzzauzfw911702_climatisation_without_external_power
          
      - type: entities
        title: Volkswagen Location
        show_header_toggle: false
        entities:
          - device_tracker.wvwzzzauzfw911702
      - type: entities
        entities:
          - automation.vw_carid_battery_fully_charged
          - automation.vw_carid_climatisation_on
          - automation.vw_carid_climatisation_off
          - automation.vw_carid_charging
          
############ AUTOMASJONER FANE ###############
  - title: Automasjoner
    icon: mdi:home-automation
    cards:
      - type: entities
        entities:
          - automation.forgot_lights
          - automation.vacuum_weekdays
      - type: entities
        title: all automations
        show_header_toggle: true
        entities:
          - automation.forgot_lights
          - automation.vw_carid_battery_fully_charged
          - automation.vw_carid_charging
          - automation.vw_carid_climatisation_off
          - automation.vw_carid_climatisation_on
          - automation.vw_charging_stopped
          - automation.vacuum_weekdays
          - automation.find_my_iphone
          - automation.tv_off_when_lights_off